name: Build CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      variant: 'Release'
    secrets: inherit
